[2024-02-26T14:07:49.640+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-18T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:49.644+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-18T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-18T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:49.712+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-18T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:49.713+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-18T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-18T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:50.088+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-02-18T00:30:00+00:00 [queued]>
[2024-02-26T14:07:50.110+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-02-18T00:30:00+00:00 [queued]>
[2024-02-26T14:07:50.111+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T14:07:50.133+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): print_current_date_with_conetxt> on 2024-02-18 00:30:00+00:00
[2024-02-26T14:07:50.141+0000] {standard_task_runner.py:57} INFO - Started process 726 to run task
[2024-02-26T14:07:50.149+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_context', 'print_current_date_with_conetxt', 'scheduled__2024-02-18T00:30:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/03-python-operator-with-context.py', '--cfg-path', '/tmp/tmp6ovfi3zr']
[2024-02-26T14:07:50.152+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask print_current_date_with_conetxt
[2024-02-26T14:07:50.217+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-18T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:50.218+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-18T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-18T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:50.221+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-02-18T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T14:07:50.361+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_context' AIRFLOW_CTX_TASK_ID='print_current_date_with_conetxt' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-18T00:30:00+00:00'
[2024-02-26T14:07:50.364+0000] {logging_mixin.py:150} INFO - execution_date: 2024-02-18
[2024-02-26T14:07:50.365+0000] {logging_mixin.py:150} INFO - execution_date_nodash: 20240218
[2024-02-26T14:07:50.366+0000] {logging_mixin.py:150} INFO - 2024-02-18는 일요일입니다.
[2024-02-26T14:07:50.367+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-02-26T14:07:50.405+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=python_dag_with_context, task_id=print_current_date_with_conetxt, execution_date=20240218T003000, start_date=20240226T140750, end_date=20240226T140750
[2024-02-26T14:07:50.450+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-26T14:07:50.491+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
