[2024-02-26T14:07:42.853+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-07T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:42.854+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-07T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-07T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:42.903+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-07T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:42.904+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-07T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-07T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:43.157+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-02-07T00:30:00+00:00 [queued]>
[2024-02-26T14:07:43.172+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-02-07T00:30:00+00:00 [queued]>
[2024-02-26T14:07:43.172+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T14:07:43.190+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): print_current_date_with_conetxt> on 2024-02-07 00:30:00+00:00
[2024-02-26T14:07:43.200+0000] {standard_task_runner.py:57} INFO - Started process 687 to run task
[2024-02-26T14:07:43.202+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_context', 'print_current_date_with_conetxt', 'scheduled__2024-02-07T00:30:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/03-python-operator-with-context.py', '--cfg-path', '/tmp/tmpxexh94jj']
[2024-02-26T14:07:43.205+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask print_current_date_with_conetxt
[2024-02-26T14:07:43.272+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-07T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:43.273+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-07T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-07T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:43.275+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-02-07T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T14:07:43.425+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_context' AIRFLOW_CTX_TASK_ID='print_current_date_with_conetxt' AIRFLOW_CTX_EXECUTION_DATE='2024-02-07T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-07T00:30:00+00:00'
[2024-02-26T14:07:43.427+0000] {logging_mixin.py:150} INFO - execution_date: 2024-02-07
[2024-02-26T14:07:43.428+0000] {logging_mixin.py:150} INFO - execution_date_nodash: 20240207
[2024-02-26T14:07:43.429+0000] {logging_mixin.py:150} INFO - 2024-02-07는 수요일입니다.
[2024-02-26T14:07:43.430+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-02-26T14:07:43.446+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=python_dag_with_context, task_id=print_current_date_with_conetxt, execution_date=20240207T003000, start_date=20240226T140743, end_date=20240226T140743
[2024-02-26T14:07:43.500+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-26T14:07:43.523+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
