[2024-02-26T14:36:12.556+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_jinja/run_id=scheduled__2024-02-11T00:30:00+00:00/task_id=print_current_date_with_jinja permission to 509
[2024-02-26T14:36:12.559+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_jinja/run_id=scheduled__2024-02-11T00:30:00+00:00/task_id=print_current_date_with_jinja permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_jinja/run_id=scheduled__2024-02-11T00:30:00+00:00/task_id=print_current_date_with_jinja'
[2024-02-26T14:36:12.641+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_jinja/run_id=scheduled__2024-02-11T00:30:00+00:00/task_id=print_current_date_with_jinja permission to 509
[2024-02-26T14:36:12.642+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_jinja/run_id=scheduled__2024-02-11T00:30:00+00:00/task_id=print_current_date_with_jinja permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_jinja/run_id=scheduled__2024-02-11T00:30:00+00:00/task_id=print_current_date_with_jinja'
[2024-02-26T14:36:13.015+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_jinja.print_current_date_with_jinja scheduled__2024-02-11T00:30:00+00:00 [queued]>
[2024-02-26T14:36:13.046+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_jinja.print_current_date_with_jinja scheduled__2024-02-11T00:30:00+00:00 [queued]>
[2024-02-26T14:36:13.056+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T14:36:13.183+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): print_current_date_with_jinja> on 2024-02-11 00:30:00+00:00
[2024-02-26T14:36:13.227+0000] {standard_task_runner.py:57} INFO - Started process 1351 to run task
[2024-02-26T14:36:13.261+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_jinja', 'print_current_date_with_jinja', 'scheduled__2024-02-11T00:30:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/04-python-operator-with-jinja.py', '--cfg-path', '/tmp/tmplv7uzvpj']
[2024-02-26T14:36:13.295+0000] {standard_task_runner.py:85} INFO - Job 88: Subtask print_current_date_with_jinja
[2024-02-26T14:36:13.621+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_jinja/run_id=scheduled__2024-02-11T00:30:00+00:00/task_id=print_current_date_with_jinja permission to 509
[2024-02-26T14:36:13.621+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_jinja/run_id=scheduled__2024-02-11T00:30:00+00:00/task_id=print_current_date_with_jinja permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_jinja/run_id=scheduled__2024-02-11T00:30:00+00:00/task_id=print_current_date_with_jinja'
[2024-02-26T14:36:13.624+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_jinja.print_current_date_with_jinja scheduled__2024-02-11T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T14:36:14.308+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_jinja' AIRFLOW_CTX_TASK_ID='print_current_date_with_jinja' AIRFLOW_CTX_EXECUTION_DATE='2024-02-11T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-11T00:30:00+00:00'
[2024-02-26T14:36:14.318+0000] {logging_mixin.py:150} INFO - 2024-02-11는 일요일입니다.
[2024-02-26T14:36:14.330+0000] {python.py:183} INFO - Done. Returned value was: 2024-02-11
[2024-02-26T14:36:14.375+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=python_dag_with_jinja, task_id=print_current_date_with_jinja, execution_date=20240211T003000, start_date=20240226T143613, end_date=20240226T143614
[2024-02-26T14:36:14.579+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-26T14:36:14.650+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
