[2024-02-26T14:07:43.100+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-09T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:43.101+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-09T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-09T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:43.133+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-09T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:43.133+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-09T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-09T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:43.372+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-02-09T00:30:00+00:00 [queued]>
[2024-02-26T14:07:43.391+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-02-09T00:30:00+00:00 [queued]>
[2024-02-26T14:07:43.391+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T14:07:43.414+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): print_current_date_with_conetxt> on 2024-02-09 00:30:00+00:00
[2024-02-26T14:07:43.422+0000] {standard_task_runner.py:57} INFO - Started process 689 to run task
[2024-02-26T14:07:43.426+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_context', 'print_current_date_with_conetxt', 'scheduled__2024-02-09T00:30:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/03-python-operator-with-context.py', '--cfg-path', '/tmp/tmpwaajwcu7']
[2024-02-26T14:07:43.428+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask print_current_date_with_conetxt
[2024-02-26T14:07:43.480+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-09T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:43.481+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-09T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-02-09T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:43.483+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-02-09T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T14:07:43.603+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_context' AIRFLOW_CTX_TASK_ID='print_current_date_with_conetxt' AIRFLOW_CTX_EXECUTION_DATE='2024-02-09T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-09T00:30:00+00:00'
[2024-02-26T14:07:43.604+0000] {logging_mixin.py:150} INFO - execution_date: 2024-02-09
[2024-02-26T14:07:43.605+0000] {logging_mixin.py:150} INFO - execution_date_nodash: 20240209
[2024-02-26T14:07:43.606+0000] {logging_mixin.py:150} INFO - 2024-02-09는 금요일입니다.
[2024-02-26T14:07:43.607+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-02-26T14:07:43.617+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=python_dag_with_context, task_id=print_current_date_with_conetxt, execution_date=20240209T003000, start_date=20240226T140743, end_date=20240226T140743
[2024-02-26T14:07:43.641+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-26T14:07:43.662+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
