[2024-02-26T14:07:26.582+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-13T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:26.586+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-13T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-13T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:26.655+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-13T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:26.660+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-13T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-13T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:27.018+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-01-13T00:30:00+00:00 [queued]>
[2024-02-26T14:07:27.033+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-01-13T00:30:00+00:00 [queued]>
[2024-02-26T14:07:27.034+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T14:07:27.062+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): print_current_date_with_conetxt> on 2024-01-13 00:30:00+00:00
[2024-02-26T14:07:27.079+0000] {standard_task_runner.py:57} INFO - Started process 608 to run task
[2024-02-26T14:07:27.082+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_context', 'print_current_date_with_conetxt', 'scheduled__2024-01-13T00:30:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/03-python-operator-with-context.py', '--cfg-path', '/tmp/tmpf3qg63fx']
[2024-02-26T14:07:27.084+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask print_current_date_with_conetxt
[2024-02-26T14:07:27.181+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-13T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:27.182+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-13T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-13T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:27.184+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-01-13T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T14:07:27.328+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_context' AIRFLOW_CTX_TASK_ID='print_current_date_with_conetxt' AIRFLOW_CTX_EXECUTION_DATE='2024-01-13T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-13T00:30:00+00:00'
[2024-02-26T14:07:27.330+0000] {logging_mixin.py:150} INFO - execution_date: 2024-01-13
[2024-02-26T14:07:27.331+0000] {logging_mixin.py:150} INFO - execution_date_nodash: 20240113
[2024-02-26T14:07:27.333+0000] {logging_mixin.py:150} INFO - 2024-01-13는 토요일입니다.
[2024-02-26T14:07:27.333+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-02-26T14:07:27.351+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=python_dag_with_context, task_id=print_current_date_with_conetxt, execution_date=20240113T003000, start_date=20240226T140727, end_date=20240226T140727
[2024-02-26T14:07:27.383+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-26T14:07:27.409+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
